# @package _global_

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '_'
        item_sep: '/'
        exclude_keys:
          - run_config
          - distributed_training.distributed_port
          - distributed_training.distributed_world_size
          - model.pretrained_model_path
          - model.target_network_path
          - next_script
          - task.cache_in_scratch
          - task.data
          - checkpoint.save_interval_updates
          - checkpoint.keep_interval_updates
          - checkpoint.save_on_overflow
          - common.log_interval
          - common.user_dir
  sweep:
    dir: /fsx-wav2vec/${env:USER}/${env:PREFIX}/${hydra.job.config_name}_${hydra.launcher.gpus_per_node}/${hydra.job.override_dirname}
    subdir: ''
  launcher:
    submitit_folder: ${hydra.sweep.dir}/submitit
    timeout_min: 4320
    cpus_per_task: 10
    gpus_per_node: 8
    tasks_per_node: 8
    mem_gb: 0
    nodes: 8
    name: pt
    partition: wav2vec
    max_num_timeout: 30
    exclude: a100-st-p4d24xlarge-471

distributed_training:
  distributed_world_size: 64
  ddp_backend: legacy_ddp
