# @package _global_

hydra:
  job:
    config:
      override_dirname:
        kv_sep: ':'
        item_sep: '__'
        exclude_keys:
          - run_config
          - distributed_training.distributed_port
  sweep:
    dir: /checkpoint/${env:USER}/${env:PREFIX}/${hydra.job.config_name}_${hydra.launcher.gpus_per_node}/${hydra.job.override_dirname}
    subdir: ${hydra.job.num}
  launcher:
    submitit_folder: ${hydra.sweep.dir}
    timeout_min: 4320
    cpus_per_task: 80
    gpus_per_node: 8
    tasks_per_node: 1
    mem_gb: 450
    nodes: 16
    name: ${env:PREFIX}_${hydra.job.config_name}
    partition: learnlab,learnfair,scavenge
    constraint: volta32gb
    max_num_timeout: 30
    exclude: learnfair1381,learnfair5192,learnfair2304